apiVersion: v1
kind: Namespace
metadata:
  name: runners
---
apiVersion: v1
kind: Secret
metadata:
  name: deployer-secrets
  namespace: runners
data:
  KUBE_CONFIG: ${KUBE_CONFIG}
  GITHUB_ACTIONS_TOKEN: ${DOCKER_REGISTRY_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: deployer-config
  namespace: runners
data:
  GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
  GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: deployer-pod
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployer
  template:
    metadata:
      labels:
        app: deployer
    spec:
      containers:
        - name: deployer-dind
          image: docker:dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: DOCKER_TLS_CERTDIR
              value: ""
        - name: deployer
          image: ghcr.io/ricardosantos-pt/actions_runner_in_docker:latest
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
            - name: builder-cache
              mountPath: /home/useragent/.cache_volume
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: GITHUB_ACTIONS_URL
              valueFrom:
                configMapKeyRef:
                  name: deployer-config
                  key: GITHUB_ACTIONS_URL
            - name: GITHUB_ACTIONS_AGENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: deployer-config
                  key: GITHUB_ACTIONS_AGENT_NAME
            - name: GITHUB_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: deployer-secrets
                  key: GITHUB_ACTIONS_TOKEN
            - name: KUBE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: deployer-secrets
                  key: KUBE_CONFIG
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: builder-cache
          emptyDir: {}
