apiVersion: v1
kind: Namespace
metadata:
  name: runners
---
apiVersion: v1
kind: Secret
metadata:
  name: builder-secrets
  namespace: runners
data:
  GITHUB_ACTIONS_TOKEN: ${DOCKER_REGISTRY_TOKEN}
  DOCKER_REGISTRY_TOKEN: ${DOCKER_REGISTRY_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: builder-config
  namespace: runners
data:
  GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
  GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
  DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
  DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
---
apiVersion: apps/v1
kind: Pod
metadata:
  name: bulder-pod
  namespace: runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: builder
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
        - name: builder-dind
          image: docker:dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: DOCKER_TLS_CERTDIR
              value: ""
        - name: builder
          image: ghcr.io/ricardosantos-pt/actions_runner_in_docker:latest
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
            - name: builder-cache
              mountPath: /home/useragent/.cache_volume
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: GITHUB_ACTIONS_URL
              valueFrom:
                configMapKeyRef:
                  name: builder-config
                  key: GITHUB_ACTIONS_URL
            - name: GITHUB_ACTIONS_AGENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: builder-config
                  key: GITHUB_ACTIONS_AGENT_NAME
            - name: GITHUB_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: builder-secrets
                  key: GITHUB_ACTIONS_TOKEN
            - name: DOCKER_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: builder-config
                  key: DOCKER_REGISTRY_URL
            - name: DOCKER_REGISTRY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: builder-config
                  key: DOCKER_REGISTRY_USERNAME
            - name: DOCKER_REGISTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: builder-secrets
                  key: DOCKER_REGISTRY_TOKEN
      volumes:
        - name: data-volume
          emptyDir: {}
        - name: builder-cache
          emptyDir: {}
