apiVersion: v1
kind: Namespace
metadata:
  name: actions-runners
---
apiVersion: v1
kind: Secret
metadata:
  name: actions-builder-secrets
  namespace: actions-runners
data:
  GITHUB_ACTIONS_TOKEN: ${DOCKER_REGISTRY_TOKEN}
  DOCKER_REGISTRY_TOKEN: ${DOCKER_REGISTRY_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-builder-config
  namespace: actions-runners
data:
  GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
  GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
  DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
  DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-builder-deployment
  namespace: actions-runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-builder
  template:
    metadata:
      labels:
        app: actions-builder
    spec:
      containers:
        - name: actions-builder-dind
          image: docker:dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: DOCKER_TLS_CERTDIR
              value: ""
        - name: actions-builder
          image: ghcr.io/ricardosantos-pt/actions_runner_in_docker/builder:latest
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: GITHUB_ACTIONS_URL
              valueFrom:
                configMapKeyRef:
                  name: actions-builder-config
                  key: GITHUB_ACTIONS_URL
            - name: GITHUB_ACTIONS_AGENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: actions-builder-config
                  key: GITHUB_ACTIONS_AGENT_NAME
            - name: GITHUB_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: actions-builder-secrets
                  key: GITHUB_ACTIONS_TOKEN
            - name: DOCKER_REGISTRY_URL
              valueFrom:
                configMapKeyRef:
                  name: actions-builder-config
                  key: DOCKER_REGISTRY_URL
            - name: DOCKER_REGISTRY_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: actions-builder-config
                  key: DOCKER_REGISTRY_USERNAME
            - name: DOCKER_REGISTRY_TOKEN
              valueFrom:
                secretKeyRef:
                  name: actions-builder-secrets
                  key: DOCKER_REGISTRY_TOKEN
      volumes:
        - name: data-volume
          emptyDir: {}
