apiVersion: v1
kind: Namespace
metadata:
  name: actions-runners
---
apiVersion: v1
kind: Secret
metadata:
  name: actions-deployer-secrets
  namespace: actions-runners
data:
  KUBE_CONFIG: ${KUBE_CONFIG}
  GITHUB_ACTIONS_TOKEN: ${DOCKER_REGISTRY_TOKEN}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: actions-deployer-config
  namespace: actions-runners
data:
  GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
  GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: actions-deployer-deployment
  namespace: actions-runners
spec:
  replicas: 1
  selector:
    matchLabels:
      app: actions-deployer
  template:
    metadata:
      labels:
        app: actions-deployer
    spec:
      containers:
        - name: actions-deployer-dind
          image: docker:dind
          securityContext:
            privileged: true
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375/
            - name: DOCKER_TLS_CERTDIR
              value: ""
        - name: actions-deployer
          image: ghcr.io/ricardosantos-pt/actions_runner_in_docker/deployer:latest
          volumeMounts:
            - name: data-volume
              mountPath: /home/useragent/_work
          env:
            - name: DOCKER_HOST
              value: tcp://docker-actions-deployer:2375/
            - name: GITHUB_ACTIONS_URL
              valueFrom:
                configMapKeyRef:
                  name: actions-deployer-config
                  key: GITHUB_ACTIONS_URL
            - name: GITHUB_ACTIONS_AGENT_NAME
              valueFrom:
                configMapKeyRef:
                  name: actions-deployer-config
                  key: GITHUB_ACTIONS_AGENT_NAME
            - name: GITHUB_ACTIONS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: actions-deployer-secrets
                  key: GITHUB_ACTIONS_TOKEN
            - name: KUBE_CONFIG
              valueFrom:
                secretKeyRef:
                  name: actions-deployer-secrets
                  key: KUBE_CONFIG
      volumes:
        - name: data-volume
          emptyDir: {}
