# Use root/example as user/password credentials
version: '3.1'

services:

  docker-github-builder:
    container_name: docker-github-builder
    restart: unless-stopped
    image: docker:dind
    privileged: true
    networks:
      - net_github_builder
    volumes:
      - data-volume:/home/useragent/_work:rw
    environment:
      DOCKER_HOST: tcp://localhost:2375/
      DOCKER_TLS_CERTDIR: ""

  github-runner-builder:
    container_name: github-runner-builder
    restart: unless-stopped
    image: ghcr.io/ricardosantos-pt/actions_runner_in_docker/builder:latest
    networks:
      - net_github_builder
    volumes:
      - data-volume:/home/useragent/_work:rw
    environment:
      DOCKER_HOST: tcp://docker-github-builder:2375/
      GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
      GITHUB_ACTIONS_TOKEN: ${GITHUB_ACTIONS_TOKEN}
      GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
      DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}
      DOCKER_REGISTRY_USERNAME: ${DOCKER_REGISTRY_USERNAME}
      DOCKER_REGISTRY_TOKEN: ${DOCKER_REGISTRY_TOKEN}

networks:
  net_github_builder:

volumes:
  data-volume: #volume to map files from github runner with docker container so they can translate to the same address on github actions