# Use root/example as user/password credentials
version: '3.1'

services:
  docker-github-deployer:
    container_name: docker-github-deployer
    restart: unless-stopped
    image: docker:dind
    privileged: true
    networks:
      - net_github_deployer
    volumes:
      - data-volume:/home/useragent/_work:rw
    environment:
      DOCKER_HOST: tcp://localhost:2375/
      DOCKER_TLS_CERTDIR: ""

  github-runner-deployer:
    container_name: github-runner-deployer
    build:
      dockerfile: "Dockerfile"
    restart: unless-stopped
    networks:
      - net_github_deployer
    volumes:
      - data-volume:/home/useragent/_work:rw
    environment:
      DOCKER_HOST: tcp://docker-github-deployer:2375/    
      GITHUB_ACTIONS_URL: ${GITHUB_ACTIONS_URL}
      GITHUB_ACTIONS_TOKEN: ${GITHUB_ACTIONS_TOKEN}
      GITHUB_ACTIONS_AGENT_NAME: ${GITHUB_ACTIONS_AGENT_NAME}
      KUBE_CONFIG: ${KUBE_CONFIG}

networks:
  net_github_deployer:

volumes:
  data-volume: #volume to map files from github runner with docker container so they can translate to the same address on github actions